version: '3.5'
services:
  pg-carBox:
    hostname: pg-carBox
    container_name: pg-carBox
    image: postgres:14
    environment:
      - POSTGRES_MULTIPLE_DATABASE=apiman.keycloak
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin123!
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: "./common/create-multiple-postgresql-databases.sh"
        target: /docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - type: volume
        source: postgres_data
        target: /var/lib/postgres
      - type: volume
        source: postgres_logs
        target: /var/log/postgres
      #- type: volume
       # source: postgres_data
       # target: /var/lib/postgres
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      #- ./docker/volumes/postgresql/:/var/lib/postgresql/data
    restart: unless-stopped
  keycloak-carBox:
    #haha
    #Be sure to use ‘docker-compose up --build -d’ to import realms.
    #docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:21.1.1 start-dev
    image: quay.io/keycloak/keycloak:21.1.2
    #image: keycloak
    hostname: keycloak-carbox
    container_name: keycloak-carbox
    restart: always
    entrypoint: [ '/bin/bash', '-c']
    command:
        - |
          cd /opt/keycloak
          ./bin/kc.sh build
          ./bin/kc.sh start-dev --import-realm --log=console --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
          ./bin/kcadm.sh config credentials --server http://137.74.160.180:8180 --realm master --user admin
          ./bin/kcadm.sh update realms/master -s sslRequired=NONE

    #2 last commands are for dev only IMPORTANT
    #command: start
    environment:
      KEYCLOAK_REALM: keycloak
      KEYCLOAK_APIMAN_API_SECRET: 42r3pHmVjMNk83KYrF3
      KEYCLOAK_APIMAN_UI_SECRET: BVDrpduftBrFBJJaIF8
      KEYCLOAK_GATEWAY_SECRET: BEenlQzJTIkdZ0BioX0
      KEYCLOAK_REALM_CERTIFICATE: MIICmzCCAYMCBgGKPKFlzDANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZhcGltYW4wHhcNMjMwODI4MTQ1MDI0WhcNMzMwODI4MTQ1MjA0WjARMQ8wDQYDVQQDDAZhcGltYW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCOM7bwhT5sDIbtU7BNbijDC/mFgoXNlPPY+PfDCH5LU1264n0Y2WyGlW90WUeyOot+bF+B86gvOquW/av0EMR692zdyjnWlgwqUYQvxh1u0GCJKZvcah4uOifJQVHL/1ZK91pQJxRD+Mn/42Lk+aIB8H7Okdn1kYaal8Z1+mqViYgV+KCQ2fu94hH8tO/aOkXBt7H0T4QzyNutYxWjwcgeuWLYcOBikSpoJgHC3XnhWoy8m1cZoWCIAU90fTlVOJ7K3mZTsuosBlCsc4PH9xja5SUx0WgFJUNgU6M1g2ZF61c4ur7oBPZB1oFHyXQE1v/JaSSw+czU/rmjDdsQY5CnAgMBAAEwDQYJKoZIhvcNAQELBQADggEBACVvyTOtBHboyPPkLgcGTZwOe+PCiX2JWiHFN2D/NqV9jyI4TBaMiJtQ3xXdAp8b+PkJ5z1F8k0OSNVdOVgKQfXHlIcoqv+rTpaa5dossG7z0DhCIPXZfadFjvY6RVH9pCIGCzrrvmdBX6k3hPUF1kbGzrbdhtGYaYDSvOJpUac3VjbSXqtIpPw98S9rGesnWo5e0RtsZthkOd+iToJ1Nr4f9cm61p8YdkIx+KD6b7MuNvlZXy6t7Ex608CJSMNrZzwBP6hWMzqwqk8JKLkBrRSP3bJDtN07tViZayz/CLr7YC7YDcirC4cS/MVdDqMopi8A1gd3tUbXaeveRpWEqqk=
      KEYCLOAK_REALM_PRIVATE_KEY: MIIEowIBAAKCAQEAjjO28IU+bAyG7VOwTW4owwv5hYKFzZTz2Pj3wwh+S1NduuJ9GNlshpVvdFlHsjqLfmxfgfOoLzqrlv2r9BDEevds3co51pYMKlGEL8YdbtBgiSmb3GoeLjonyUFRy/9WSvdaUCcUQ/jJ/+Ni5PmiAfB+zpHZ9ZGGmpfGdfpqlYmIFfigkNn7veIR/LTv2jpFwbex9E+EM8jbrWMVo8HIHrli2HDgYpEqaCYBwt154VqMvJtXGaFgiAFPdH05VTieyt5mU7LqLAZQrHODx/cY2uUlMdFoBSVDYFOjNYNmRetXOLq+6AT2QdaBR8l0BNb/yWkksPnM1P65ow3bEGOQpwIDAQABAoIBACRl+lKQWI0Bm9vNixgWtVpPi1vwL92SXeRQveJvHxyaxygZ5xlgNdYxE+k9HQvyzlfa14uE2azVIKyyW7xKOnCbOoN+ytUxbQW7/dDYrhn6Pmt9egauJvGAM0ThclV8ExN3Que3SQmo+dOE2YBwoVZLv7mSPa8Mw954MPVr1rJVr4SCJ0YwyoCklYxwRdvCgRhF72qSEo04upwPa+KLCoMIVUGTP7NwCP6Ney8uSrJ+jrJOnLvXlQv3tICOFeLWiV/UO/0Y/nC3X/XXWOav4V0/LH68uzM8GZZHa0z3GRi8efJh3ofs4Ew47nwHTQiL51X2V8IhL9HUPgdq6FHVnNECgYEA+ad7WLMQ+Kuq7HX47Wwrwz/Go5WrrypvRrKfE1A08TcnFoSN5fFALWI+ZjHAUjaeWgcK4p9l3BYForZ6RK4uV4wGF8LldaN5mDCApN5ZKLimxpDb3D2ZUJUcVkut6K8eZUAbZjFS8bcJpCPABtw9IAk7kA3F/FJJYQ7vXDH2QukCgYEAkdEIjdzG6SLst3r0rv+jo/5BdG0dcZPOkuhE4y36q69SkIt9QsS0lswW65GzqKt2ul1WPAFsUreXZ3RHEruTIksiyEvHOHiml7dHLOUOqzbKrnGxaFBa7vUjKZ/jptOHoq2eT2R2xZrpg0knhQ8xWsUkiQROx/bbgAxYPxkPXQ8CgYB+qUxZSjBYGbCUW545xuHFI7xCDpOWQW9HbSRsBgt2Pkckk4fym5216NxDuQYcL/3TKzOImtpw+PNPBEmwQrbcT/xfXdBRCOmOHz2FaBHQKS7kG2aQrOf2DFDeL3NCVGaVdBrylB/C5tyLXF/2mxKgCE8h3PsP8yeriIpEOkz40QKBgE9EHKxReee+ToQnWN/Qo/o/+wD5V+on+UGu9dOxaPTvZ6ify0YCfFEFPOht2gY0v2Pr3TbdZy9IEgvxD7nFMeSQh6XuW6v9GkKbJRvooKK+NEvEDjawh94icCzud+h2UONEEi0CZfZhkdMGb29LpP688HFzYAgfz466JzaVvt5NAoGBANrWX1nJ4V5KmWretvdwkHL3Ub/lq0uBYMFca8an195D8AgswKrHtGKIlGP//zHMR/uM8NvYAK2UoScSx5jWlDbKgnyZ5o2Pnd1UxWf8hShPQk6iMjyROotQy+CRvjj8j4MwhZf1sNxYKTVXVVSI6Vew4Hbi5aOS/0LqU/WI1PVb
      KEYCLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjjO28IU+bAyG7VOwTW4owwv5hYKFzZTz2Pj3wwh+S1NduuJ9GNlshpVvdFlHsjqLfmxfgfOoLzqrlv2r9BDEevds3co51pYMKlGEL8YdbtBgiSmb3GoeLjonyUFRy/9WSvdaUCcUQ/jJ/+Ni5PmiAfB+zpHZ9ZGGmpfGdfpqlYmIFfigkNn7veIR/LTv2jpFwbex9E+EM8jbrWMVo8HIHrli2HDgYpEqaCYBwt154VqMvJtXGaFgiAFPdH05VTieyt5mU7LqLAZQrHODx/cY2uUlMdFoBSVDYFOjNYNmRetXOLq+6AT2QdaBR8l0BNb/yWkksPnM1P65ow3bEGOQpwIDAQAB
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123!
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://pg-carBox:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin123!
      JDBC_PARAMS: "useSSL=false"
      # General KC config
      KC_HEALTH_ENABLED: "true"
    volumes:
      - type: bind
        source: "./data/apiman-realm-for-keycloak.json"
        target: /opt/keycloak/data/import/apiman-realm-for-keycloak.json
      - type: bind
        source: "./data/apiman-keycloak-theme.jar"
        target: /opt/keycloak/providers/apiman-keycloak-theme.jar
      #- ./keycloak.key:/etc/x509/https/tls.key
      #- ./keycloak.crt:/etc/x509/https/tls.crt
      #- ./keycloak/conf:/opt/keycloak/conf
      #- ./docker/images/keycloak/realms:/opt/keycloak/data/import
      #- ./keycloak/themes:/opt/keycloak/themes
      #- ./keycloak/config/realm-export.json:/tmp/keycloak/config/realm-export.json
      #- ./keycloak/config/realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8180:8080
      - 8443:8443
    depends_on:
      - pg-carBox
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: carbox@carbox.com
      defaultEmail: carbox@carbox.com
      defaultPassword: carbox
      PGADMIN_DEFAULT_PASSWORD: carbox
  portainer:
    image: 'portainer/portainer-ce:latest'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
volumes:
  portainer_data: { }




